apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: clusterissuer
    app.kubernetes.io/part-of: mystore-platform
    environment: staging
spec:
  acme:
    # Let's Encrypt Staging server
    # Use this for testing - certificates won't be trusted by browsers
    # But it has relaxed rate limits
    server: https://acme-staging-v02.api.letsencrypt.org/directory

    # Email for urgent renewal and security notices
    # IMPORTANT: Change this to your email!
    email: your-email@example.com

    # Secret to store ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging-account-key

    # Solvers for ACME challenges
    solvers:
    # HTTP-01 challenge solver
    # This creates a temporary Ingress/Service to prove domain ownership
    # Works for most cases, requires port 80 accessible from internet
    - http01:
        ingress:
          # Use the default ingress class (will be Kong or nginx)
          ingressClassName: kong
          # Optional: add annotations for specific ingress controllers
          # podTemplate:
          #   metadata:
          #     annotations:
          #       konghq.com/strip-path: "true"

      # Optional: specify which domains this solver applies to
      # selector:
      #   dnsNames:
      #   - 'api.mystore.com.br'
      #   - '*.api.mystore.com.br'

    # DNS-01 challenge solver (for wildcard certificates)
    # Uncomment and configure if you need wildcard certs
    # Requires DNS provider integration (Cloudflare, Route53, etc.)
    # - dns01:
    #     cloudflare:
    #       email: your-cloudflare-email@example.com
    #       apiTokenSecretRef:
    #         name: cloudflare-api-token
    #         key: api-token
    #   selector:
    #     dnsNames:
    #     - '*.mystore.com.br'
    #     - 'mystore.com.br'
