# Example Certificate using self-signed issuer
# Use this as a template for your own certificates
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-mystore-cert
  namespace: default
  labels:
    app.kubernetes.io/name: example-certificate
    app.kubernetes.io/part-of: mystore-platform
spec:
  # Name of the Secret that will store the certificate
  # This Secret will be created automatically by cert-manager
  secretName: example-mystore-tls

  # Certificate duration (default: 90 days)
  duration: 2160h # 90 days

  # Renew certificate this long before expiry (default: 30 days)
  renewBefore: 720h # 30 days

  # Subject Alternative Names (SANs) - DNS names for the certificate
  dnsNames:
    - example.mystore.local
    - www.example.mystore.local
    - api.example.mystore.local

  # Subject information
  subject:
    organizations:
      - MyStore
    organizationalUnits:
      - Platform Engineering
    countries:
      - BR
    localities:
      - São Paulo
    provinces:
      - SP

  # Common Name (CN) - usually the primary domain
  commonName: example.mystore.local

  # Is this a CA certificate?
  isCA: false

  # Private key configuration
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    # For better performance and security, consider ECDSA:
    # algorithm: ECDSA
    # size: 256

  # Key usages
  usages:
    - server auth  # For HTTPS servers
    - client auth  # For mTLS client authentication
    # - digital signature
    # - key encipherment

  # Reference to the Issuer/ClusterIssuer
  issuerRef:
    name: selfsigned-ca
    kind: ClusterIssuer
    group: cert-manager.io

  # Optional: Certificate template (advanced)
  # secretTemplate:
  #   annotations:
  #     my-annotation: "example"
  #   labels:
  #     my-label: "example"

---
# Example: Certificate for Let's Encrypt Staging
# This shows how to get a real (but untrusted) certificate from Let's Encrypt
# Uncomment to use (requires public domain and HTTP/HTTPS access)

# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: letsencrypt-example
#   namespace: default
# spec:
#   secretName: letsencrypt-example-tls
#   duration: 2160h
#   renewBefore: 720h
#   dnsNames:
#     - your-domain.com  # CHANGE THIS!
#     - www.your-domain.com  # CHANGE THIS!
#   issuerRef:
#     name: letsencrypt-staging
#     kind: ClusterIssuer
#     group: cert-manager.io

---
# Example: Using certificate in an Ingress
# cert-manager can automatically create certificates for Ingress resources
# Just add the annotation and specify the secret name

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: example-ingress
#   namespace: default
#   annotations:
#     # This annotation tells cert-manager to create a certificate
#     cert-manager.io/cluster-issuer: selfsigned-ca
# spec:
#   ingressClassName: kong
#   tls:
#   - hosts:
#     - example.mystore.local
#     secretName: example-ingress-tls  # cert-manager creates this automatically
#   rules:
#   - host: example.mystore.local
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: my-service
#             port:
#               number: 80

---
# Verification Commands:
#
# 1. Apply this example:
#    kubectl apply -f example-certificate.yaml
#
# 2. Wait for certificate to be ready:
#    kubectl wait --for=condition=ready certificate example-mystore-cert
#
# 3. Check certificate status:
#    kubectl get certificate example-mystore-cert
#    kubectl describe certificate example-mystore-cert
#
# 4. View the Secret created:
#    kubectl get secret example-mystore-tls
#
# 5. Inspect the certificate:
#    kubectl get secret example-mystore-tls -o jsonpath='{.data.tls\.crt}' | base64 -d | openssl x509 -noout -text
#
# 6. View expiry date:
#    kubectl get secret example-mystore-tls -o jsonpath='{.data.tls\.crt}' | base64 -d | openssl x509 -noout -dates
#
# 7. Check if cert-manager is managing it:
#    kubectl get certificaterequest
#
# 8. View events for troubleshooting:
#    kubectl describe certificate example-mystore-cert
#    kubectl get events --sort-by='.lastTimestamp' | grep -i certificate
